server:
  port: 3000

spring:
  datasource:
    username: root
    password: ObBDMmQm6Xao/s1y+JXlnLriLBEJTdKLvR1BSk6ErRtpVckfk2KOgPoic6/PeUI/yKQSO5j5QmaZSKmIRpirXA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.222.73:3306/Enchanted-Club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 1234567890
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIvbdkR2QlrkJxaX1EMhgvSTBi426ONwVtino26L20/vFsNA/vMtvabGN3zB6/l7LcmDjpdKKfu6r0WCrzF6R9kCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml