server:
  port: 9001

spring:
  application:
    name: EnchantedShop-user-service

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/EnchantedShop_User?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567890
# redis配置
  redis:
    host: 60.204.222.73
    port: 8000
    password: Enchanted0v0Redis@.

  #邮箱服务配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: summerdayxumeng@163.com #发送邮件的邮箱地址
    password: SOTMXALMJLQNJGCR #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: summerdayxumeng@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#配置mybatis plus控制台打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tEANbjYESui31oPtoEF
    access-key-secret: tlxDCNe65WYiH9wg3L9OuaB9K4qezT
    bucketname: enchanted-shop-img